/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/R6QUKZEaj7G
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"
import { JSX, SVGProps } from "react"
import Image from "next/image"


export function ImageSlider() {
  return (
    <div className="flex flex-col items-center justify-center w-full py-12 md:py-24 lg:py-32">
      <div className="max-w-6xl w-full">
        <Carousel className="rounded-lg overflow-hidden">
          <CarouselContent>
            <CarouselItem>
              <Image
                alt="Slide 1"
                className="aspect-[2/1] object-cover"
                height={600}
                src="/belt.jpg"
                width={1200}
              />
            </CarouselItem>
            <CarouselItem>
              <Image
                alt="Slide 2"
                className="aspect-[2/1] object-cover"
                height={600}
                src="/dog.jpg"
                width={1200}
              />
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious className="absolute left-4 top-1/2 -translate-y-1/2 rounded-full bg-white/50 p-2 text-gray-900 hover:bg-white/80 focus:outline-none focus:ring-2 focus:ring-gray-950 dark:bg-gray-950/50 dark:text-gray-50 dark:hover:bg-gray-800/80 dark:focus:ring-gray-300">
            <ChevronLeftIcon className="h-6 w-6" />
          </CarouselPrevious>
          <CarouselNext className="absolute right-4 top-1/2 -translate-y-1/2 rounded-full bg-white/50 p-2 text-gray-900 hover:bg-white/80 focus:outline-none focus:ring-2 focus:ring-gray-950 dark:bg-gray-950/50 dark:text-gray-50 dark:hover:bg-gray-800/80 dark:focus:ring-gray-300">
            <ChevronRightIcon className="h-6 w-6" />
          </CarouselNext>
        </Carousel>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
// npx v0 add xDbeuQNmXQb