/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xDbeuQNmXQb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"
import Image from "next/image"

export function ImageCarousel() {
  return (
    <div className="w-full max-w-5xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-gray-50">Boosted Advert</h2>
        <div className="flex items-center space-x-2">
          <button className="p-2 rounded-full text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-gray-950 dark:focus-visible:ring-gray-300">
            <ChevronLeftIcon className="h-5 w-5" />
            <span className="sr-only">Previous</span>
          </button>
          <button className="p-2 rounded-full text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-gray-950 dark:focus-visible:ring-gray-300">
            <ChevronRightIcon className="h-5 w-5" />
            <span className="sr-only">Next</span>
          </button>
        </div>
      </div>
      <div className="overflow-x-auto -mx-4 sm:-mx-6 lg:-mx-8 scrollbar-hide">
        <div className="inline-flex space-x-4">
          <div className="flex-shrink-0 w-[280px] sm:w-[320px] lg:w-[360px]">
            <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-950">
              <Image
                alt="Product Image"
                className="w-full h-[200px] sm:h-[240px] lg:h-[280px] object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <div className="p-4 sm:p-6">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-lg font-bold text-gray-900 dark:text-gray-50">Stylish Sunglasses</p>
                  <p className="text-lg font-bold text-primary">$29.99</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">UV protection, durable frame</p>
                <Button className="w-full" size="sm">
                  Buy
                </Button>
              </div>
            </div>
          </div>
          <div className="flex-shrink-0 w-[280px] sm:w-[320px] lg:w-[360px]">
            <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-950">
              <Image
                alt="Product Image"
                className="w-full h-[200px] sm:h-[240px] lg:h-[280px] object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <div className="p-4 sm:p-6">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-lg font-bold text-gray-900 dark:text-gray-50">Leather Crossbody Bag</p>
                  <p className="text-lg font-bold text-primary">$49.99</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">Stylish and practical</p>
                <Button className="w-full" size="sm">
                  Buy
                </Button>
              </div>
            </div>
          </div>
          <div className="flex-shrink-0 w-[280px] sm:w-[320px] lg:w-[360px]">
            <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-950">
              <Image
                alt="Product Image"
                className="w-full h-[200px] sm:h-[240px] lg:h-[280px] object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <div className="p-4 sm:p-6">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-lg font-bold text-gray-900 dark:text-gray-50">Wireless Headphones</p>
                  <p className="text-lg font-bold text-primary">$79.99</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">High-quality sound</p>
                <Button className="w-full" size="sm">
                  Buy
                </Button>
              </div>
            </div>
          </div>
          <div className="flex-shrink-0 w-[280px] sm:w-[320px] lg:w-[360px]">
            <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-950">
              <Image
                alt="Product Image"
                className="w-full h-[200px] sm:h-[240px] lg:h-[280px] object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <div className="p-4 sm:p-6">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-lg font-bold text-gray-900 dark:text-gray-50">Classic Wristwatch</p>
                  <p className="text-lg font-bold text-primary">$59.99</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">Timeless design</p>
                <Button className="w-full" size="sm">
                  Buy
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
